Drop dependency on `daemon` package

diff --git a/deb/build/debian/jenkins.init b/deb/build/debian/jenkins.init
--- a/deb/build/debian/jenkins.init
+++ b/deb/build/debian/jenkins.init
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env /lib/init/init-d-script
 # /etc/init.d/jenkins
 # debian-compatible jenkins startup script.
 # Amelia A Lewis <alewis@ibco.com>
@@ -13,91 +13,54 @@
 # Description:       Controls @@SUMMARY@@
 ### END INIT INFO
 
-PATH=/bin:/usr/bin:/sbin:/usr/sbin
-
+DAEMON=none
+COMMAND_NAME=java
+NAME="@@ARTIFACTNAME@@"
 DESC="@@SUMMARY@@"
-NAME=@@ARTIFACTNAME@@
-SCRIPTNAME=/etc/init.d/${NAME}
 
-[ -r /etc/default/${NAME} ] && . /etc/default/${NAME}
+check_arguments() {
+	# Exit if not supposed to run standalone
+	if [ "${RUN_STANDALONE}" = "false" ]; then
+		echo "ERROR: Not configured to run standalone" >&2
+		return 2
+	fi
 
-DAEMON=/usr/bin/daemon
-DAEMON_ARGS="--name=${NAME} --inherit --env=JENKINS_HOME=${JENKINS_HOME} --output=${JENKINS_LOG} --pidfile=${PIDFILE}"
-JAVA=$(type -p java)
+	# Make sure there exists a java executable, it may not be always the case
+	JAVA=$(command -v "${COMMAND_NAME}")
+	if [ -z "${JAVA}" ]; then
+		echo "ERROR: No Java executable found in current PATH: ${PATH}" >&2
+		echo "If you actually have Java installed on the system make sure the executable is in the aforementioned path and that 'command -v ${COMMAND_NAME}' returns the Java executable path" >&2
+		return 2
+	fi
 
-if [ -n "${UMASK}" ]; then
-	DAEMON_ARGS="${DAEMON_ARGS} --umask=${UMASK}"
-fi
-if [ "${JENKINS_ENABLE_ACCESS_LOG}" = "yes" ]; then
-	JENKINS_ARGS="${JENKINS_ARGS} --accessLoggerClassName=winstone.accesslog.SimpleAccessLogger --simpleAccessLogger.format=combined --simpleAccessLogger.file=/var/log/${NAME}/access_log"
-fi
+	# Work out the JAVA version we are working with:
+	JAVA_VERSION=$("${JAVA}" -version 2>&1 | sed -n ';s/.* version "\([0-9]\{2,\}\|[0-9]\.[0-9]\)\..*".*/\1/p;')
+	if [ "${JAVA_VERSION}" = "1.8" ]; then
+		echo "Correct java version found" >&2
+	elif [ "${JAVA_VERSION}" = "11" ]; then
+		echo "Correct java version found" >&2
+	else
+		echo "Found an incorrect Java version" >&2
+		echo "Java version found:" >&2
+		"${JAVA}" -version >&2
+		echo "Aborting" >&2
+		return 2
+	fi
 
-SU=/bin/su
-
-# Exit if the package is not installed
-if [ ! -x "${DAEMON}" ]; then
-	echo "daemon package not installed" >&2
-	exit 1
-fi
-
-# Exit if not supposed to run standalone
-if [ "${RUN_STANDALONE}" = "false" ]; then
-	echo "Not configured to run standalone" >&2
-	exit 1
-fi
-
-# Make sure there exists a java executable, it may not be always the case
-if [ -z "${JAVA}" ]; then
-	echo "ERROR: No Java executable found in current PATH: ${PATH}" >&2
-	echo "If you actually have java installed on the system make sure the executable is in the aforementioned path and that 'type -p java' returns the java executable path" >&2
-	exit 1
-fi
-
-# Which Java versions can be used to run Jenkins
-JAVA_ALLOWED_VERSIONS=("1.8" "11")
-# Work out the JAVA version we are working with:
-JAVA_VERSION=$(${JAVA} -version 2>&1 | sed -n ';s/.* version "\([0-9]\{2,\}\|[0-9]\.[0-9]\)\..*".*/\1/p;')
-
-if [[ ${JAVA_ALLOWED_VERSIONS[*]} =~ ${JAVA_VERSION} ]]; then
-	echo "Correct java version found" >&2
-else
-	echo "Found an incorrect Java version" >&2
-	echo "Java version found:" >&2
-	${JAVA} -version >&2
-	echo "Aborting" >&2
-	exit 1
-fi
-
-# load environments
-if [ -r /etc/default/locale ]; then
-	. /etc/default/locale
-	export LANG LANGUAGE
-elif [ -r /etc/environment ]; then
-	. /etc/environment
-	export LANG LANGUAGE
-fi
-
-# Load the VERBOSE setting and other rcS variables
-. /lib/init/vars.sh
-
-# Define LSB log_* functions.
-# Depend on lsb-base (>= 3.0-6) to ensure that this file is present.
-. /lib/lsb/init-functions
-
-# Make sure we run as root, since setting the max open files through
-# ulimit requires root access
-if [ "$(id -u)" -gt 0 ]; then
-	echo "The ${NAME} init script can only be run as root"
-	exit 1
-fi
+	# Make sure we run as root, since setting the max open files through
+	# ulimit requires root access
+	if [ "$(id -u)" -gt 0 ]; then
+		echo "The ${NAME} init script can only be run as root" >&2
+		return 2
+	fi
+}
 
 check_tcp_port() {
-	local service=$1
-	local assigned=$2
-	local default=$3
-	local assigned_address=$4
-	local default_address=$5
-	local port
+	service=$1
+	assigned=$2
+	default=$3
+	assigned_address=$4
+	default_address=$5
 
 	if [ -n "${assigned}" ]; then
 		port=${assigned}
@@ -116,25 +79,26 @@ check_tcp_port() {
 	if [ "${count}" -gt 0 ]; then
 		echo "The selected ${service} port (${port}) on address ${address} seems to be in use by another program "
 		echo "Please select another address/port combination to use for ${NAME}"
-		return 1
+		return 2
 	fi
 }
 
-#
-# Function that starts the daemon/service
-#
-do_start() {
-	# the default location is /var/run/jenkins/jenkins.pid but the parent directory needs to be created
-	mkdir "$(dirname "${PIDFILE}")" >/dev/null 2>&1 || true
-	chown "${JENKINS_USER}" "$(dirname "${PIDFILE}")"
-	# Return
-	#   0 if daemon has been started
-	#   1 if daemon was already running
-	#   2 if daemon could not be started
-	${DAEMON} ${DAEMON_ARGS} --running && return 1
+do_start_cmd_override() {
+	check_arguments || return 2
 
-	# Verify if there is a jenkins process already running without a daemon
-	get_running || return 2
+	# load environments
+	if [ -r /etc/default/locale ]; then
+		. /etc/default/locale
+		export LANG LANGUAGE
+	elif [ -r /etc/environment ]; then
+		. /etc/environment
+		export LANG LANGUAGE
+	fi
+	export JENKINS_HOME
+
+	# the default location is /var/run/jenkins/jenkins.pid but the parent directory needs to be created
+	mkdir -p "$(dirname "${PIDFILE}")" || return 2
+	chown "${JENKINS_USER}" "$(dirname "${PIDFILE}")" || return 2
 
 	# Verify that the jenkins port is not already in use, winstone does not exit
 	# even for BindException
@@ -144,186 +108,99 @@ do_start() {
 	# proper value
 	if [ -n "${MAXOPENFILES}" ]; then
 		[ "${VERBOSE}" != no ] && echo "Setting up max open files limit to ${MAXOPENFILES}"
-		ulimit -n "${MAXOPENFILES}"
+		ulimit -n "${MAXOPENFILES}" || return 2
 	fi
 	# notify of explicit umask
 	if [ -n "${UMASK}" ]; then
 		[ "${VERBOSE}" != no ] && echo "Setting umask to ${UMASK}"
 	fi
 
-	# --user in daemon doesn't prepare environment variables like HOME, USER, LOGNAME or USERNAME,
-	# so we let su do so for us now
-	${SU} -l "${JENKINS_USER}" --shell=/bin/bash -c "${DAEMON} ${DAEMON_ARGS} -- ${JAVA} ${JAVA_ARGS} -jar ${JENKINS_WAR} ${JENKINS_ARGS}" || return 2
-}
-
-#
-# Verify that all jenkins processes have been shutdown
-#
-get_running() {
-	return "$(pgrep -U "${JENKINS_USER}" -f "${JENKINS_WAR}" | grep -c .)"
-}
-
-#
-# killall jenkins processes that have not been shutdown
-#
-force_stop() {
-	if ! get_running; then
-		killall -u "${JENKINS_USER}" java daemon || return 3
-		# wait for the process to really terminate
-		for n in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20; do
-			sleep 1
-			get_running && return 0
-		done
-		return 2
+	# enable access log
+	if [ "${JENKINS_ENABLE_ACCESS_LOG}" = "yes" ]; then
+		JENKINS_ARGS="${JENKINS_ARGS} --accessLoggerClassName=winstone.accesslog.SimpleAccessLogger --simpleAccessLogger.format=combined --simpleAccessLogger.file=/var/log/${NAME}/access_log"
 	fi
+
+	# start-stop-daemon --chuid/--group doesn't prepare environment variables
+	# like HOME, USER, LOGNAME or USERNAME, so re-export these
+	SHELL=$(awk -F: "\$1 == \"${JENKINS_USER}\" {print \$NF}" /etc/passwd)
+	[ -n "${SHELL}" ] || SHELL=/bin/bash
+	HOME="${JENKINS_HOME}" \
+		SHELL="${SHELL}" \
+		USER="${JENKINS_USER}" \
+		LOGNAME="${JENKINS_USER}" \
+		USERNAME="${JENKINS_USER}" \
+		PWD="${JENKINS_HOME}" \
+		start-stop-daemon \
+		--start \
+		--quiet \
+		--oknodo \
+		--background \
+		--no-close \
+		--make-pidfile \
+		--pidfile "${PIDFILE}" \
+		--chdir "${JENKINS_HOME}" \
+		--chuid "${JENKINS_USER}" \
+		--user "${JENKINS_USER}" \
+		--group "${JENKINS_GROUP}" \
+		--name "${COMMAND_NAME}" \
+		--exec "${JAVA}" \
+		${UMASK:+--umask ${UMASK}} \
+		-- ${JAVA_ARGS} -jar "${JENKINS_WAR}" ${JENKINS_ARGS} >>"${JENKINS_LOG}" 2>&1
+	RETVAL="$?"
+	[ "${RETVAL}" = 2 ] && return 2
+	# Verify the process did in fact start successfully and didn't just bomb out
+	sleep 1
+	ATTEMPT=1
+	while [ ${ATTEMPT} -le 30 ]; do
+		pidofproc -p "${PIDFILE}" "${JAVA}" >/dev/null && break
+		[ "${ATTEMPT}" = 30 ] && return 2
+		sleep 1
+		ATTEMPT=$((ATTEMPT + 1))
+	done
+	return "${RETVAL}"
 }
 
-# Get the status of the daemon process
-get_daemon_status() {
-	${DAEMON} ${DAEMON_ARGS} --running || return 1
-}
-
-#
-# Function that stops the daemon/service
-#
-do_stop() {
-	# Return
-	#   0 if daemon has been stopped
-	#   1 if daemon was already stopped
-	#   2 if daemon could not be stopped
-	#   other if a failure occurred
-	get_daemon_status
-	case "$?" in
-	0)
-		${DAEMON} ${DAEMON_ARGS} --stop || return 2
-		# wait for the process to really terminate
-		for n in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20; do
-			sleep 1
-			${DAEMON} ${DAEMON_ARGS} --running || break
-		done
-		if get_daemon_status; then
-			force_stop || return "$?"
-		fi
-		;;
-	*)
-		force_stop || return "$?"
-		;;
-	esac
-
+do_stop_cmd_override() {
+	check_arguments || return "$?"
+	start-stop-daemon \
+		--stop \
+		--quiet \
+		--oknodo \
+		--pidfile "${PIDFILE}" \
+		--chdir "${JENKINS_HOME}" \
+		--chuid "${JENKINS_USER}" \
+		--user "${JENKINS_USER}" \
+		--group "${JENKINS_GROUP}" \
+		--name "${COMMAND_NAME}" \
+		--exec "${JAVA}" \
+		--retry=TERM/30/KILL/5
+	RETVAL="$?"
+	[ "${RETVAL}" = 2 ] && return 2
+	# Wait for children to finish too if this is a daemon that forks
+	# and if the daemon is only ever run from this initscript.
+	# If the above conditions are not satisfied then add some other code
+	# that waits for the process to drop all resources that could be
+	# needed by services started subsequently.  A last resort is to
+	# sleep for some time.
+	start-stop-daemon \
+		--stop \
+		--quiet \
+		--oknodo \
+		--pidfile "${PIDFILE}" \
+		--chdir "${JENKINS_HOME}" \
+		--chuid "${JENKINS_USER}" \
+		--user "${JENKINS_USER}" \
+		--group "${JENKINS_GROUP}" \
+		--name "${COMMAND_NAME}" \
+		--exec "${JAVA}" \
+		--retry=0/30/KILL/5
+	[ "$?" = 2 ] && return 2
 	# Many daemons don't delete their pidfiles when they exit.
 	rm -f "${PIDFILE}"
-	return 0
+	return "${RETVAL}"
 }
 
-# Verify the process did in fact start successfully and didn't just bomb out
-do_check_started_ok() {
-	sleep 1
-	if [ "$1" -gt 0 ]; then
-		return "$1"
-	fi
-	if get_running; then
-		return 2
-	else
-		return 0
-	fi
+do_status_override() {
+	check_arguments || return "$?"
+	status_of_proc "${JAVA}" "${NAME}" -p "${PIDFILE}"
 }
-
-case "$1" in
-start)
-	log_daemon_msg "Starting ${DESC}" "${NAME}"
-	do_start
-	START_STATUS="$?"
-	do_check_started_ok "${START_STATUS}"
-	case "$?" in
-	0 | 1)
-		log_end_msg 0
-		;;
-	2)
-		log_end_msg 1
-		exit 7
-		;;
-	esac
-	;;
-stop)
-	log_daemon_msg "Stopping ${DESC}" "${NAME}"
-	do_stop
-	case "$?" in
-	0 | 1)
-		log_end_msg 0
-		;;
-	2 | 3)
-		log_end_msg 1
-		exit 100
-		;;
-	esac
-	;;
-restart | force-reload)
-	#
-	# If the "reload" option is implemented then remove the
-	# 'force-reload' alias
-	#
-	log_daemon_msg "Restarting ${DESC}" "${NAME}"
-	do_stop
-	case "$?" in
-	0 | 1)
-		do_start
-		START_STATUS="$?"
-		sleep 1
-		do_check_started_ok "${START_STATUS}"
-		case "$?" in
-		0)
-			log_end_msg 0
-			;;
-		1)
-			log_end_msg 1
-			exit 100
-			;; # Old process is still running
-		*)
-			log_end_msg 1
-			exit 100
-			;; # Failed to start
-		esac
-		;;
-	*)
-		# Failed to stop
-		log_end_msg 1
-		;;
-	esac
-	;;
-status)
-	get_daemon_status
-	case "$?" in
-	0)
-		echo "${DESC} is running with the pid $(cat "${PIDFILE}")"
-		rc=0
-		;;
-	*)
-		get_running
-		procs=$?
-		if [ ${procs} -eq 0 ]; then
-			echo -n "${DESC} is not running"
-			if [ -f "${PIDFILE}" ]; then
-				echo ", but the pidfile (${PIDFILE}) still exists"
-				rc=1
-			else
-				echo
-				rc=3
-			fi
-
-		else
-			echo "${procs} instances of jenkins are running at the moment"
-			echo "but the pidfile ${PIDFILE} is missing"
-			rc=0
-		fi
-
-		exit ${rc}
-		;;
-	esac
-	;;
-*)
-	echo "Usage: ${SCRIPTNAME} {start|stop|status|restart|force-reload}" >&2
-	exit 3
-	;;
-esac
-
-exit 0
diff --git a/deb/build/debian/jenkins.postrm b/deb/build/debian/jenkins.postrm
--- a/deb/build/debian/jenkins.postrm
+++ b/deb/build/debian/jenkins.postrm
@@ -4,8 +4,16 @@ set -e
 
 case "$1" in
 purge)
-	userdel @@ARTIFACTNAME@@ || true
-	groupdel @@ARTIFACTNAME@@ || true
+	if [ -x "$(command -v deluser)" ]; then
+		deluser --quiet --system @@ARTIFACTNAME@@ >/dev/null || true
+	else
+		userdel @@ARTIFACTNAME@@ || echo "failed to remove @@ARTIFACTNAME@@ system user" >&2
+	fi
+	if [ -x "$(command -v delgroup)" ]; then
+		delgroup --quiet --system --only-if-empty @@ARTIFACTNAME@@ >/dev/null || true
+	else
+		groupdel @@ARTIFACTNAME@@ || echo "failed to remove @@ARTIFACTNAME@@ system group" >&2
+	fi
 	rm -rf /var/lib/@@ARTIFACTNAME@@ /var/log/@@ARTIFACTNAME@@ \
 		/var/run/@@ARTIFACTNAME@@ /var/cache/@@ARTIFACTNAME@@
 	;;
