Let's do the debian exit codes better

diff --git a/deb/build/debian/jenkins.init b/deb/build/debian/jenkins.init
--- a/deb/build/debian/jenkins.init
+++ b/deb/build/debian/jenkins.init
@@ -182,9 +182,10 @@ do_stop()
 
 # Verify the process did in fact start successfully and didn't just bomb out
 do_check_started_ok() {
-    if [ $1 -ne 0 ]; then return $1; fi
+    sleep 1
+    if [ "$1" -ne "0" ]; then return $1; fi
     get_running
-    if [ "$?" -eq 0 ]; then
+    if [ "$?" -eq "0" ]; then
         return 2
     else 
         return 0
@@ -199,7 +200,7 @@ case "$1" in
     do_check_started_ok "$START_STATUS"
     case "$?" in
         0|1) log_end_msg 0 ;;
-        2) log_end_msg 1 ;;
+        2) log_end_msg 1 ; exit 7 ;;
     esac
     ;;
   stop)
@@ -207,7 +208,7 @@ case "$1" in
     do_stop
     case "$?" in
         0|1) log_end_msg 0 ;;
-        2) log_end_msg 1 ;;
+        2) log_end_msg 1 ; exit 100 ;;
     esac
     ;;
   restart|force-reload)
@@ -221,11 +222,12 @@ case "$1" in
       0|1)
         do_start
         START_STATUS="$?"
+        sleep 1
         do_check_started_ok "$START_STATUS"
         case "$?" in
           0) log_end_msg 0 ;;
-          1) log_end_msg 1 ;; # Old process is still running
-          *) log_end_msg 1 ;; # Failed to start
+          1) log_end_msg 1 ; exit 100 ;; # Old process is still running
+          *) log_end_msg 1 ; exit 100 ;; # Failed to start
         esac
         ;;
       *)
