More branding

diff --git a/osx/scripts/preinstall-launchd b/osx/scripts/preinstall-launchd
--- a/osx/scripts/preinstall-launchd
+++ b/osx/scripts/preinstall-launchd
@@ -7,4 +7,4 @@ if [ -f ${JENKINS_PLIST} ]; then
 fi
 
 JENKINS_DAEMON_PLIST="/Library/LaunchDaemons/org.jenkins-ci.plist"
-launchctl unload ${JENKINS_DAEMON_PLIST} || echo 'Failed to unload old Jenkins launch daemon. Maybe it is was not loaded?'
+launchctl unload ${JENKINS_DAEMON_PLIST} || echo 'Failed to unload old @@PRODUCTNAME@@ launch daemon. Maybe it is was not loaded?'
